timezone: "Jerusalem"
services:
  applicaster2:
    name: Applicaster2
    region: us-east-1
    autoscaling_group_name: applicaster2
    levels:
      - name: Normal
        min: 6
        max: 12
        label: Normal operation
      - name: Large
        min: 12
        max: 18
        label: Large event
      - name: XLarge
        min: 18
        max: 18
        label: Huge event (required only when expected users are over 3 million)
  widgets:
    name: Widgets
    region: us-east-1
    autoscaling_group_name: widgets
    levels:
      - name: Normal
        min: 3
        max: 3
        label: Normal operation
      - name: Large
        min: 12
        max: 12
        label: Large event
  stars:
    name: Stars
    region: us-east-1
    autoscaling_group_name: stars
    levels:
      - name: Normal
        min: 3
        max: 3
        label: Normal operation
      - name: Large
        min: 6
        max: 6
        label: Large event (required only when expected users are over 3 million)
  achievement:
    name: Achievement Center
    region: eu-central-1
    autoscaling_group_name: achievement-center-baseline
    levels:
      - name: Normal
        min: 2
        max: 2
        label: Normal operation
      - name: Large
        min: 10
        max: 10
        label: Large event
      - name: XLarge
        min: 20
        max: 20
        label: Huge event (required only when expected users are over 500K)
