timezone: "Jerusalem"
services:
  applicaster2:
    name: Applicaster2
    autoscaling_group_name: applicaster2
    levels:
      - name: Normal
        min: 6
        max: 6
        label: Normal operation
      - name: Large
        min: 12
        max: 12
        label: Large event
      - name: XLarge
        min: 18
        max: 18
        label: Huge event
  widgets:
    name: Widgets
    autoscaling_group_name: widgets
    levels:
      - name: Normal
        min: 3
        max: 3
        label: Normal operation
      - name: Large
        min: 12
        max: 12
        label: Large event
  stars:
    name: Stars
    autoscaling_group_name: stars
    levels:
      - name: Normal
        min: 3
        max: 3
        label: Normal operation
      - name: Large
        min: 6
        max: 6
        label: Large event (required only when expected users are over 3 million)
